name: kSMP
version: '1.0-DEV'
description: "A fork of MCRaidz for an SMP implementation."
authors: ["Ian Rich", "Revity Studios"]
main: net.minebo.smp.kSMP
soft-depend: ["PlaceholderAPI"]
api-version: '1.20'
